# 101 Pandas Exercises for Data Analysis

*by Selva Prabhakaran*

From the website: https://www.machinelearningplus.com/python/101-pandas-exercises-python/

*101 python pandas exercises are designed to challenge your logical muscle and to help internalize data manipulation with python’s favorite package for data analysis.*
*The questions are of 3 levels of difficulties with L1 being the easiest to L3 being the hardest.*

**NOTE**: Again, its 75 not 100, but the exercises are good.

In [2]:
pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


1. (L1) **Import `pandas` and check the version**

In [3]:
import pandas as pd

pd.__version__

/tmp/ipykernel_183812/1300210777.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


'2.2.0'

2. (L1) **Create a `pandas` series from each of the items below: a list, numpy and a dictionary**

In [4]:
import numpy as np

# Inputs

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

for data in [mylist, myarr, mydict]:
    print(pd.Series(data).head())

0    a
1    b
2    c
3    e
4    d
dtype: object
0    0
1    1
2    2
3    3
4    4
dtype: int64
a    0
b    1
c    2
e    3
d    4
dtype: int64


3. (L1) **Convert the series `ser` into a dataframe with its index as another column on the dataframe.**

In [5]:
# Inputs

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

ser.to_frame().reset_index()

index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

4. (L1) **Combine `ser1` and `ser2` to form a dataframe.**

In [6]:
# Inputs

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

np.all(
    pd.DataFrame([ser1, ser2]).T  # Stacking horizontally and rotating by 90 deg
    == pd.concat([ser1, ser2], axis=1)  # Stacking rotated series
)

True

5. (L1) **Give a name to the series `ser` calling it `my_series`.**

In [7]:
# Input

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = "my_series"

ser.head()

0    a
1    b
2    c
3    e
4    d
Name: my_series, dtype: object

6. (L2) **From `ser1` remove items present in `ser2`.**

In [8]:
# Inputs

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# With numpy
with_numpy = np.setdiff1d(ser1, ser2)

# With pandas
with_pandas = ser1[~ser1.isin(ser2)]

print(with_numpy)  # Results in ndarray
print(with_pandas)  # Results in Series

[1 2 3]
0    1
1    2
2    3
dtype: int64


7. (L2) **Get the items not common to both series `ser1` and `ser2`.**

In [9]:
# Input

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = np.union1d(ser1, ser2)
intersection = np.intersect1d(ser1, ser2)

print(union, intersection)
union[~pd.Series(union).isin(intersection)]

[1 2 3 4 5 6 7 8] [4 5]


array([1, 2, 3, 6, 7, 8])

8. (L2) **Compute the minimum, 25th percentile, median, 75th, and maximum of `ser`.**

In [10]:
# Input

ser = pd.Series(np.random.normal(10, 5, 25))

for method in [pd.Series.max, pd.Series.min, pd.Series.median]:
    print(method(ser))
print(ser.quantile(0.25))
print(ser.quantile(0.75))


23.04533597490106
0.4843517421196708
9.997412163957014
5.927800776263154
13.974318855654186


9. (L2) **Calcualte the frequency counts of each unique item in `ser`.**

In [11]:
# Input

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

# Through numpy
with_numpy = np.unique(ser.to_numpy(), return_counts=True)

# Through pandas
with_pandas = ser.value_counts()

print(with_numpy)
print(with_pandas)

(array(['a', 'c', 'd', 'e', 'f', 'g', 'h'], dtype=object), array([3, 6, 9, 2, 2, 5, 3]))
d    9
c    6
g    5
a    3
h    3
e    2
f    2
Name: count, dtype: int64


10. (L2) **From `ser`, keep the top 2 most frequent items as it is and replace everything else as `Other`.**

In [12]:
# Input

np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))


ser[~ser.isin(ser.value_counts()[:2].index.to_series())] = 'Other'
print(ser)

0         1
1     Other
2     Other
3         4
4     Other
5         1
6         1
7     Other
8         4
9         4
10        4
11        4
dtype: object


/tmp/ipykernel_183812/2726137041.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Other' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ser[~ser.isin(ser.value_counts()[:2].index.to_series())] = 'Other'


11. (L2) **Bin the series `ser` into 10 equal deciles and replace the values with the bin name.**

In [13]:
# Input

ser = pd.Series(np.random.random(20))

with_cut = pd.cut(
    ser,
    bins=np.percentile(ser, np.arange(0, 110, 10)),
    labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'],
    include_lowest=True
)

with_qcut = pd.qcut(
    ser,
    q=np.arange(0, 1.1, .1),
    labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']
)

np.all(with_cut == with_qcut)

True

12. (L1) **Reshape the series `ser` into a dataframe with 7 rows and 5 columns.**

In [14]:
# Input

ser = pd.Series(np.random.randint(1, 10, 35))

pd.DataFrame(
    ser.to_numpy().reshape((7,5))
)

0  1  2  3  4
0  1  2  6  9  7
1  6  2  6  8  6
2  2  7  4  7  3
3  1  3  8  8  9
4  1  1  6  6  8
5  8  6  4  5  5
6  3  8  2  2  4

13. (L2)  **Find the positions of numbers that are multiples of 3 from `ser`.**

In [15]:
# Input

ser = pd.Series(np.random.randint(1, 10, 7))

print(ser)
np.argwhere(ser.to_numpy() % 3 == 0)

0    6
1    5
2    1
3    6
4    4
5    4
6    7
dtype: int64


array([[0],
       [3]])

14. (L1) **From `ser`, extract the items at positions in list `pos`.**

In [16]:
# Input

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

np.all(ser[pos] == ser.take(pos))

True

15. (L1) **Stack two series vertically and horizontally.**

In [17]:
# Input

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

horizontally = pd.concat([ser1, ser2], axis=0)
vertically = pd.concat([ser1, ser2], axis=1)
print(horizontally, vertically)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object    0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


16. (L2) **Get the positions of items of `ser2` in `ser1` as a list.**

In [18]:
# Input

ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

np.argwhere(
    ser1.isin(ser2).to_numpy()
)

array([[0],
       [4],
       [5],
       [8]])

17. (L2) **Compute the mean squared error of `truth` and `pred`.**

**NOTE**: This question means that we need to calculate the mean squared error between the two series, using the formula:

$$MSE = \dfrac{1}{n} * \sum \left(truth - pred\right)^2$$

In [19]:
# Input

truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean(
    (truth-pred)**2  # Squares of errors
)

0.2989757084109758

18. (L2) **Convert the first character of each element in `ser` to uppercase.**

In [20]:
# Input

ser = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.apply(str.title)

0     How
1      To
2    Kick
3    Ass?
dtype: object

19. (L2) **Calculate the number of characters in each word in `ser`.**

In [21]:
# Input

ser = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.apply(len)

0    3
1    2
2    4
3    4
dtype: int64

20. (L2) **Compute the difference of differences between consecutive numbers in `ser`.**

In [22]:
# Input

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

ser.diff().diff()

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64

21. (L2) **Convert a series of date-strings to a timeseries**

Desired output:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

In [23]:
# Input

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

ser.astype('datetime64[ns]')

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

22. (L2) **Get the day of month, week number, day of year and day of week from `ser`.**

Desired output:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [24]:
# Input

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Manual

dates = []
week_numbers = []
day_numbers = []
weekdays = []
weekday_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Friday']

for index, date in enumerate(ser.astype('datetime64[ns]')):
    dates.append(index)
    week_numbers.append(date.week)
    day_numbers.append(date.day_of_year)
    weekdays.append(weekday_names[date.weekday()])

print('Manual')
print(dates)
print(week_numbers)
print(day_numbers)
print(weekdays)

# With 'dt' property (incomplete)

import dateutil

timeseries = ser.map(dateutil.parser.parse)

print('\nThrough API')
print(timeseries.dt.day.to_list())
#print(timeseries.dt.weekofyear.to_list()) Doesn't work anymore, maybe API changed!
print(timeseries.dt.day_of_year.to_list())
print(timeseries.dt.weekday.map(lambda weekday_number: weekday_names[weekday_number]).to_list())

Manual
[0, 1, 2, 3, 4, 5]
[53, 5, 9, 14, 19, 23]
[1, 33, 63, 94, 125, 157]
['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

Through API
[1, 2, 3, 4, 5, 6]
[1, 33, 63, 94, 125, 157]
['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


23. (L2) **Change `ser` to dates that start with 4th of the respective months.**

In [25]:
# Input

ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

import datetime
def shift_day(day_string: str) -> datetime.datetime:
    return dateutil.parser.parse(f'4th {day_string}')

pd.Series(
    np.vectorize(shift_day)(ser)
)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

24. (L3) **From `ser`, extract words that contain atleast 2 vowels.**

In [26]:
# Input

ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

def count_vowels(word: str) -> int:
    return len([
        letter
        for letter in np.array([*word.lower()])
        if letter in ['a', 'e', 'i', 'o', 'u']
    ])

ser[
    ser.map(count_vowels) >= 2  # This serves as mask for the ser Series
]

0     Apple
1    Orange
4     Money
dtype: object

25. (L3) **Extract the valid `emails` from the series emails. The regex pattern for valid emails is provided as reference.**

In [27]:
# Input

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

import re

emails[
    emails.map(
        lambda input_email: re.compile(pattern).match(input_email)
    ).values != None
]

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

26. (L2) **Compute the mean of `weights` of each `fruit`.**

In [47]:
# Inputs

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

fruits_dataframe = pd.DataFrame(
    np.vstack([fruit, weights])
).T
fruits_dataframe.columns = ["fruit", "weight"]
fruits_dataframe.groupby('fruit').mean()

weight
fruit           
apple        8.0
banana  5.666667
carrot  4.333333

27. (L2) **Compute the euclidean distance between series (points) p and q, without using a packaged formula.**

In [56]:
# Inputs

p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

via_dataframe = np.sqrt(
    pd.DataFrame([p,q]).T.apply(lambda row: (row[1]-row[0])**2, axis=1).sum(axis=0)
)
via_norm = np.sqrt(np.sum((q-p)**2))

np.isclose(via_dataframe, via_norm)

True

28. (L3) **Get the positions of peaks (values surrounded by smaller values on both sides) in `ser`.**

In [119]:
# Input

ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# From NumPy exercises
a_diffs = np.sign(np.diff(np.hstack([ser[0], ser])))
[
    diff_index
    for diff_index in range(len(a_diffs[1:]))
    if a_diffs[diff_index] == 1 and a_diffs[diff_index+1] == -1  # Signs of differences: (+1) / [MAX] \ (-1)
]

[1, 5, 7]

29. (L3) **Replace missing spaces in the string `my_str` with the least frequent character.**

In [126]:
# Input

my_str = 'dbc deb abed gade'

uniques, counts = np.unique(
    pd.Series([*my_str]),
    return_counts=True
)
least_frequent_character = uniques[np.argmin(counts)]

my_str.replace(' ', least_frequent_character)

'dbccdebcabedcgade'

30. (L3) **Create a TimeSeries starting `2000-01-01` and 10 weekends (saturdays) after that having random numbers as values.**

In [134]:
pd.DataFrame({
    'date': pd.date_range('2020-01-01', periods=10, freq='7D'),
    'number': np.random.randint(low=0, high=100, size=10)
})

date  number
0 2020-01-01      68
1 2020-01-08      68
2 2020-01-15      73
3 2020-01-22      20
4 2020-01-29      21
5 2020-02-05      39
6 2020-02-12      78
7 2020-02-19      81
8 2020-02-26      13
9 2020-03-04      45

31. (L2) **`ser` has missing dates and values. Make all missing dates appear and fill up with value from previous date.**


In [182]:
# Input

ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

'''
From docs:

Series.resample: method for frequency conversion and resampling of time series

Here: instead of sampling at random days, we shift the frequency to ONE DAY and then fill missing values with ffill
'''
ser.resample('D').ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

32. (L3) **Compute autocorrelations for the first 10 lags of `ser`. Find out which lag has the largest correlation.**

Desired output:

```python
# values will change due to randomness
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
Lag having highest correlation:  9
```

In [211]:
# Input

ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorrelations = pd.Series([
    ser.autocorr(lag)
    for lag in range(1,11)
])

print(autocorrelations.to_list())
print(autocorrelations.copy().abs().argmax() + 1)

[0.3211960338570503, 0.057645487382609426, -0.19737614519082788, -0.5228361130502509, -0.0319066559961901, -0.06466514594224611, 0.09567362817266578, 0.22167672391435844, -0.15854946940451373, 0.12106496947970609]
4


33. (L2) **Import every 50th row of `boston` dataset as a dataframe.**

In [221]:
import requests

BOSTON_URL = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"

boston = pd.DataFrame(
    np.genfromtxt(BOSTON_URL, delimiter=',', dtype=str)
)
boston

0     1        2       3      4      5      6       7      8   \
0     "crim"  "zn"  "indus"  "chas"  "nox"   "rm"  "age"   "dis"  "rad"   
1    0.00632    18     2.31     "0"  0.538  6.575   65.2    4.09      1   
2    0.02731     0     7.07     "0"  0.469  6.421   78.9  4.9671      2   
3    0.02729     0     7.07     "0"  0.469  7.185   61.1  4.9671      2   
4    0.03237     0     2.18     "0"  0.458  6.998   45.8  6.0622      3   
..       ...   ...      ...     ...    ...    ...    ...     ...    ...   
502  0.06263     0    11.93     "0"  0.573  6.593   69.1  2.4786      1   
503  0.04527     0    11.93     "0"  0.573   6.12   76.7  2.2875      1   
504  0.06076     0    11.93     "0"  0.573  6.976     91  2.1675      1   
505  0.10959     0    11.93     "0"  0.573  6.794   89.3  2.3889      1   
506  0.04741     0    11.93     "0"  0.573   6.03   80.8   2.505      1   

        9          10      11       12      13  
0    "tax"  "ptratio"     "b"  "lstat"  "medv"  
1      296       15.3   396.9     4.98      24  
2      242       17.8   396.9     9.14    21.6  
3      242       17.8  392.83     4.03    34.7  
4      222       18.7  394.63     2.94    33.4  
..     ...        ...     ...      ...     ...  
502    273         21  391.99     9.67    22.4  
503    273         21   396.9     9.08    20.6  
504    273         21   396.9     5.64    23.9  
505    273         21  393.45     6.48      22  
506    273         21   396.9     7.88    11.9  

[507 rows x 14 columns]